# Generated by Django 3.1.3 on 2021-11-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211105_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coin',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
