# Generated by Django 3.1.3 on 2021-11-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coin',
            field=models.IntegerField(null=True),
        ),
    ]
