# Generated by Django 3.2.9 on 2021-11-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='writer',
        ),
    ]
