# Generated by Django 3.1.3 on 2021-12-24 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('사회', '사회'), ('과학', '과학'), ('예술', '예술'), ('기타', '기타')], default='기타', max_length=20)),
                ('info_text', models.TextField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('대여 가능', '대여 가능'), ('대여중', '대여중')], default='대여가능', max_length=10)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now=True, null=True)),
                ('borrow_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.majorbook')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
