# Generated by Django 3.2.9 on 2021-11-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('category', models.TextField(choices=[('IT', 'IT'), ('인문', '인문'), ('사회', '사회'), ('과학', '과학'), ('예술', '예술')], default='IT')),
                ('info_text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('status', models.CharField(choices=[('대여 가능', '대여 가능'), ('대여중', '대여중')], default='대여가능', max_length=10)),
            ],
        ),
    ]
