# Generated by Django 3.2.9 on 2021-11-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorbook',
            name='info_text',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('category', models.TextField(choices=[('IT', 'IT'), ('인문', '인문'), ('사회', '사회'), ('과학', '과학'), ('예술', '예술')], default='IT')),
                ('book_pk', models.CharField(max_length=30)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
