# Generated by Django 3.2.9 on 2021-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorbook',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='majorbook',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
    ]
