# Generated by Django 3.2 on 2021-11-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorbook',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('인문', '인문'), ('사회', '사회'), ('과학', '과학'), ('예술', '예술')], default='IT', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
