# Generated by Django 3.2.9 on 2021-11-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211103_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowBook',
        ),
    ]
