# Generated by Django 3.2 on 2021-11-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20211103_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='majorbook',
            old_name='image',
            new_name='img',
        ),
    ]
