# Generated by Django 3.1.3 on 2021-11-04 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_borrowedbook_borrowed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='book_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.majorbook'),
        ),
    ]
