# Generated by Django 3.2 on 2021-11-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_image_majorbook_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorbook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='majorbook',
            name='img',
        ),
        migrations.RemoveField(
            model_name='majorbook',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='majorbook',
            name='status',
        ),
        migrations.RemoveField(
            model_name='majorbook',
            name='upload_date',
        ),
    ]
