# Generated by Django 3.2 on 2021-11-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20211103_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorbook',
            name='category',
            field=models.TextField(choices=[('IT', 'IT'), ('인문', '인문'), ('사회', '사회'), ('과학', '과학'), ('예술', '예술')], default='IT'),
        ),
        migrations.AddField(
            model_name='majorbook',
            name='status',
            field=models.CharField(choices=[('대여 가능', '대여 가능'), ('대여중', '대여중')], default='대여가능', max_length=10),
        ),
    ]
