# Generated by Django 3.2 on 2021-11-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20211103_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorbook',
            name='pub_date',
            field=models.DateField(default='####-##-##'),
        ),
        migrations.AddField(
            model_name='majorbook',
            name='upload_date',
            field=models.DateTimeField(default=''),
        ),
    ]
