# Generated by Django 3.2 on 2021-11-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20211103_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorbook',
            name='pub_date',
            field=models.DateField(default=''),
        ),
    ]
