# Generated by Django 3.2 on 2021-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_majorbook_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorbook',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='majorbook',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
