# Generated by Django 3.2 on 2021-11-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20211103_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorbook',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='majorbook',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='majorbook',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
    ]
